//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodeGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ioport_set_pin_dir($PINNAME$,$IOPORT_DIR$);.
        /// </summary>
        internal static string PinDirectionCode {
            get {
                return ResourceManager.GetString("PinDirectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ioport_set_pin_sense_mode($PINNAME$,$IOPORT_SENSE_MODE$);.
        /// </summary>
        internal static string PinInputSenseModeCode {
            get {
                return ResourceManager.GetString("PinInputSenseModeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ioport_set_pin_mode($PINNAME$,$IOPORT_MODE$);.
        /// </summary>
        internal static string PinOutputPullConfigCode {
            get {
                return ResourceManager.GetString("PinOutputPullConfigCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ioport_set_pin_level($PINNAME$,$IOPORT_LEVEL$);.
        /// </summary>
        internal static string PinOutputValueCode {
            get {
                return ResourceManager.GetString("PinOutputValueCode", resourceCulture);
            }
        }
    }
}
